FROM ocaml/opam:alpine-ocaml-4.14@sha256:32dde8d3eaad0bcfacc18cd4c9c940d3c75e08b196a878117f84e9c7e500dea6 AS build
RUN sudo apk update && sudo apk add libev capnproto m4 sqlite libgmpxx
RUN sudo ln -f /usr/bin/opam-2.1 /usr/bin/opam && opam init --reinit -ni
RUN cd ~/opam-repository && git fetch -q origin master && git reset --hard 5d3f0d1d655199e596a1e785e69fae8fad78cad3 && opam update
COPY --chown=opam ocluster-api.opam ocluster-worker.opam ocluster.opam /src/
COPY --chown=opam obuilder/obuilder.opam obuilder/obuilder-spec.opam /src/obuilder/
RUN opam pin -yn /src/obuilder/
WORKDIR /src
RUN opam install -y --deps-only .
ADD --chown=opam . .
RUN opam exec -- dune subst
RUN opam exec -- dune build ./_build/install/default/bin/ocluster-worker

FROM alpine:3.20
RUN apk update && apk add docker libev curl gnupg git sqlite
WORKDIR /var/lib/ocluster-worker
ENTRYPOINT ["/usr/local/bin/ocluster-worker"]
ENV PROGRESS_NO_TRUNC=1
COPY --from=build /src/_build/install/default/bin/ocluster-worker /usr/local/bin/
