{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ocluster_pool_queue_length",
     "legendFormat": "{{pool}}-{{queue}}-{{priority}}"
    }
   ]
  },
  {
   "title": "Workers connected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ocluster_pool_workers_connected",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Running jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ocluster_worker_running_jobs", "legendFormat": "{{worker}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "Submitted jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ocluster_scheduler_client_submitted_jobs",
     "legendFormat": "{{client}}-{{pool}}-{{priority}}"
    }
   ]
  },
  {
   "title": "OCaml heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "ocaml_gc_heap_words * 8", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Jobs started",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ocluster_pool_jobs_accepted_total",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}